#!/usr/bin/env python3
"""Emit LaTeX tables + prose macros from results/*.json.

Every table fragment and every macro is written unconditionally with a "--"
fallback, so paper/main.tex compiles whether or not experiments have run yet.
Re-run this after run_all.py to fill real numbers; the manuscript prose pulls
headline numbers from tables/macros.tex, so nothing is hard-coded in main.tex.
"""
from __future__ import annotations
import json, sys
from pathlib import Path

RES = Path("results")
OUT = Path("paper/tables"); OUT.mkdir(parents=True, exist_ok=True)

CORE = [("cifar10", "badnets", "CIFAR-10 / BadNets"),
        ("cifar10", "blend", "CIFAR-10 / Blend"),
        ("mnist", "badnets", "MNIST / BadNets"),
        ("mnist", "blend", "MNIST / Blend")]
DET_ROWS = [("xu", "Xu \\emph{et al.}~\\cite{xu2025attention}"),
            ("neural_cleanse", "Neural Cleanse~\\cite{wang2019neuralcleanse}"),
            ("strip", "STRIP~\\cite{gao2019strip}"),
            ("abl", "ABL~\\cite{li2021abl}"),
            ("single_layer", "Single-layer attention"),
            ("mlaf_bd", "\\textbf{MLAF-BD (ours)}")]
ABL_ROWS = [("A_last", "A: last layer only (prior-work proxy)"),
            ("B_first_last", "B: first $+$ last layer"),
            ("C_concat_xgb", "C: all layers, concat, XGB"),
            ("D_wla_xgb", "D: all layers $+$ WLA, XGB"),
            ("E_full", "E: all $+$ WLA $+$ ensemble (full)"),
            ("F_no_drift", "F: E, remove Drift"),
            ("G_no_entropy", "G: E, remove Entropy"),
            ("H_no_kl", "H: E, remove KL"),
            ("I_no_variance", "I: E, remove Variance")]
FEATS = ["drift", "entropy", "kl_div", "concentration", "energy", "variance", "sparsity"]
FEAT_LABEL = {"drift": "Attention Drift (novel)", "entropy": "Entropy", "kl_div": "KL divergence",
              "concentration": "Concentration", "energy": "Energy", "variance": "Variance",
              "sparsity": "Sparsity"}


def load():
    data = {}
    for j in RES.glob("*.json"):
        if j.stem in ("summary", "env") or j.stem.endswith("_arrays"):
            continue
        try:
            d = json.load(open(j))
            data[(d["dataset"], d["attack"], d["backbone"].split("_")[0])] = d
        except Exception:
            pass
    return data


def tag(d, a, bb="vit"):
    return (d, a, bb)


def fmt(x, nd=1):
    try:
        if x != x:
            return "--"
        return f"{float(x):.{nd}f}"
    except Exception:
        return "--"


def g(data, key, *path, default=None):
    cur = data.get(key)
    for p in path:
        if cur is None:
            return default
        cur = cur.get(p) if isinstance(cur, dict) else None
    return cur if cur is not None else default


def main_results(data):
    heads = " & ".join(f"\\multicolumn{{2}}{{c}}{{{lab}}}" for *_ , lab in CORE)
    sub = " & ".join(["ACC & F1"] * len(CORE))
    lines = [
        "% AUTOGENERATED by scripts/make_tables.py -- do not edit by hand",
        "\\begin{table*}[t]", "\\centering",
        "\\caption{Detection performance (\\%). Values are the mean over seeds; ``--'' marks a"
        " configuration not yet run. MLAF-BD uses the full $R^{84}$ feature matrix.}",
        "\\label{tab:main}", "\\footnotesize", "\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{l" + "cc" * len(CORE) + "}", "\\toprule",
        "Method & " + heads + " \\\\",
        " & " + sub + " \\\\", "\\midrule"]
    for dk, dl in DET_ROWS:
        cells = []
        for d, a, _ in CORE:
            cells.append(fmt(g(data, tag(d, a), "detectors", dk, "acc")))
            cells.append(fmt(g(data, tag(d, a), "detectors", dk, "f1")))
        row = dl + " & " + " & ".join(cells) + " \\\\"
        if dk == "mlaf_bd":
            lines.append("\\midrule")
        lines.append(row)
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}"]
    (OUT / "main_results.tex").write_text("\n".join(lines) + "\n")


def ablation(data):
    d = data.get(tag("cifar10", "badnets"))
    baseF = g(data, tag("cifar10", "badnets"), "ablation", "A_last", "f1")
    lines = [
        "% AUTOGENERATED", "\\begin{table}[t]", "\\centering",
        "\\caption{Ablation on CIFAR-10 $+$ BadNets. $\\Delta$F1 is relative to the"
        " single-layer baseline (A). ``--'' marks results not yet computed.}",
        "\\label{tab:ablation}", "\\footnotesize", "\\begin{tabular}{lcccc}", "\\toprule",
        "Configuration & ACC & F1 & AUC & $\\Delta$F1 \\\\", "\\midrule"]
    for k, lab in ABL_ROWS:
        acc = g(data, tag("cifar10", "badnets"), "ablation", k, "acc")
        f1 = g(data, tag("cifar10", "badnets"), "ablation", k, "f1")
        auc = g(data, tag("cifar10", "badnets"), "ablation", k, "auc")
        if f1 is not None and baseF is not None:
            delta = f"{f1 - baseF:+.1f}"
        else:
            delta = "--"
        if k == "F_no_drift":
            lines.append("\\midrule")
        lines.append(f"{lab} & {fmt(acc)} & {fmt(f1)} & {fmt(auc,3)} & {delta} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    (OUT / "ablation.tex").write_text("\n".join(lines) + "\n")


def mitigation(data):
    lines = [
        "% AUTOGENERATED", "\\begin{table}[t]", "\\centering",
        "\\caption{Two-stage mitigation. CDA: clean detection accuracy; ASR: attack"
        " success rate (lower is better after mitigation).}",
        "\\label{tab:mitigation}", "\\footnotesize", "\\begin{tabular}{lcccc}", "\\toprule",
        "Configuration & CDA$_{\\text{pre}}$ & CDA$_{\\text{post}}$ &"
        " ASR$_{\\text{pre}}$ & ASR$_{\\text{post}}$ \\\\", "\\midrule"]
    for d, a, lab in CORE:
        lines.append(" & ".join([lab,
            fmt(g(data, tag(d, a), "cda_pre")), fmt(g(data, tag(d, a), "cda_post")),
            fmt(g(data, tag(d, a), "asr_pre")), fmt(g(data, tag(d, a), "asr_post"))]) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    (OUT / "mitigation.tex").write_text("\n".join(lines) + "\n")


def feature_corr(data):
    lines = [
        "% AUTOGENERATED", "\\begin{table}[t]", "\\centering",
        "\\caption{Mean absolute Pearson correlation of each feature with the poison"
        " label, aggregated over all layers. Attention Drift is the strongest single"
        " feature on CIFAR-10/BadNets and stays informative elsewhere, though entropy"
        " and KL divergence are comparable on MNIST and Blend.}",
        "\\label{tab:featcorr}", "\\footnotesize", "\\begin{tabular}{l" + "c" * len(CORE) + "}",
        "\\toprule", "Feature & " + " & ".join(lab for *_, lab in CORE) + " \\\\", "\\midrule"]
    for f in FEATS:
        cells = [fmt(g(data, tag(d, a), "feature_correlation", f, default=None), 3) for d, a, _ in CORE]
        lines.append(f"{FEAT_LABEL[f]} & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    (OUT / "feature_corr.tex").write_text("\n".join(lines) + "\n")


def extended(data):
    ext = [(d, a, bb) for (d, a, bb) in data if (d, a, bb) not in [(x, y, "vit") for x, y, _ in CORE]]
    lines = ["% AUTOGENERATED", "\\begin{table}[t]", "\\centering",
        "\\caption{Extended robustness: MLAF-BD vs.\\ the strongest baseline on the"
        " additional attacks, dataset (GTSRB) and backbone (DeiT-S).}",
        "\\label{tab:extended}", "\\footnotesize", "\\begin{tabular}{lllcc}", "\\toprule",
        "Dataset & Attack & Backbone & MLAF-BD F1 & Best baseline F1 \\\\", "\\midrule"]
    if not ext:
        lines.append("\\multicolumn{5}{c}{\\emph{run \\texttt{scripts/run\\_all.py} to populate}} \\\\")
    for d, a, bb in sorted(ext):
        mf = g(data, (d, a, bb), "detectors", "mlaf_bd", "f1")
        base = max([g(data, (d, a, bb), "detectors", k, "f1") or 0 for k in ("xu", "strip", "neural_cleanse", "abl")] or [0])
        lines.append(f"{d} & {a} & {bb} & {fmt(mf)} & {fmt(base)} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    (OUT / "extended.tex").write_text("\n".join(lines) + "\n")


def macros(data):
    def acc(d, a): return fmt(g(data, tag(d, a), "detectors", "mlaf_bd", "acc"))
    def f1(d, a): return fmt(g(data, tag(d, a), "detectors", "mlaf_bd", "f1"))
    # drift-removal effect on the stealthy Blend attack (where it is largest);
    # on BadNets the features are redundant and the effect is ~0.
    ef = g(data, tag("cifar10", "blend"), "ablation", "E_full", "f1")
    ff = g(data, tag("cifar10", "blend"), "ablation", "F_no_drift", "f1")
    drift_drop = f"{ef - ff:.1f}" if (ef is not None and ff is not None) else "--"
    m = {
        "MLAFCifarBadAcc": acc("cifar10", "badnets"), "MLAFCifarBadF": f1("cifar10", "badnets"),
        "MLAFCifarBleAcc": acc("cifar10", "blend"), "MLAFCifarBleF": f1("cifar10", "blend"),
        "MLAFMnistBadAcc": acc("mnist", "badnets"), "MLAFMnistBadF": f1("mnist", "badnets"),
        "MLAFMnistBleAcc": acc("mnist", "blend"), "MLAFMnistBleF": f1("mnist", "blend"),
        "DriftDropF": drift_drop,
        "AsrPreCifar": fmt(g(data, tag("cifar10", "badnets"), "asr_pre")),
        "AsrPostCifar": fmt(g(data, tag("cifar10", "badnets"), "asr_post")),
        "AsrPreMnist": fmt(g(data, tag("mnist", "badnets"), "asr_pre")),
        "AsrPostMnist": fmt(g(data, tag("mnist", "badnets"), "asr_post")),
        "NCAnomaly": fmt(g(data, tag("cifar10", "badnets"), "nc", "anomaly_index"), 2),
    }
    lines = ["% AUTOGENERATED prose macros -- \\input by main.tex"]
    for k, v in m.items():
        lines.append(f"\\newcommand{{\\{k}}}{{{v}}}")
    (OUT / "macros.tex").write_text("\n".join(lines) + "\n")


def main():
    data = load()
    print(f"make_tables: found {len(data)} result file(s)")
    main_results(data); ablation(data); mitigation(data)
    feature_corr(data); extended(data); macros(data)
    print(f"wrote tables + macros to {OUT}")


if __name__ == "__main__":
    main()
